<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2010/04/03 17:46:00
sfConfig::add(array(
  'app_sympal_config_theme' => array (
  'enabled' => true,
  'default_theme' => 'default',
  'allow_changing_theme_by_url' => true,
  'theme_request_parameter_name' => 'sf_sympal_theme',
  'modules' => 
  array (
  ),
  'routes' => 
  array (
  ),
),
  'app_sympal_config_themes' => array (
  'default' => 
  array (
    'available' => true,
    'disabled' => false,
    'layout' => 'default',
    'stylesheets' => 
    array (
      0 => '/sfSympalThemePlugin/css/default.css',
    ),
  ),
  'wordpress_default' => 
  array (
    'available' => true,
    'disabled' => false,
    'layout' => 'wordpress',
    'stylesheets' => 
    array (
      0 => '/sfSympalThemePlugin/css/wordpress.css',
    ),
  ),
  'sympal' => 
  array (
    'available' => true,
    'disabled' => false,
    'layout' => 'sympal',
    'stylesheets' => 
    array (
      0 => '/sfSympalThemePlugin/css/sympal.css',
    ),
  ),
),
  'app_sympal_config_offline' => array (
  'enabled' => false,
  'module' => 'sympal_default',
  'action' => 'offline',
),
  'app_sympal_config_rich_date_forms' => array (
  'sfSympalContentForm' => 
  array (
    0 => 'date_published',
  ),
  'sfSympalMenuItemForm' => 
  array (
    0 => 'date_published',
  ),
),
  'app_sympal_config_default_culture' => 'en',
  'app_sympal_config_date_published_format' => 'D',
  'app_sympal_config_inline_editing' => array (
  'enabled' => true,
  'default_column_form' => 'sfSympalInlineEditContentColumnForm',
  'default_slot_form' => 'sfSympalInlineEditContentSlotForm',
  'default_form_renderer' => 'sympal_edit_slot/slot_editor_form',
  'default_edit_mode' => 'popup',
),
  'app_sympal_config_default_rendering_module' => 'sympal_content_renderer',
  'app_sympal_config_default_rendering_action' => 'index',
  'app_sympal_config_default_content_template' => 'sympal_default/default_content_template',
  'app_sympal_config_google_analytics_code' => NULL,
  'app_sympal_config_default_install_content_type_menu' => 'primary',
  'app_sympal_config_user_model' => 'sfGuardUser',
  'app_sympal_config_group_model' => 'sfGuardGroup',
  'app_sympal_config_permission_model' => 'sfGuardPermission',
  'app_sympal_config_success_signin_url' => NULL,
  'app_sympal_config_recaptcha_forms' => array (
  0 => 'sfGuardRegisterForm',
),
  'app_sympal_config_sympal_name' => 'Sympal',
  'app_sympal_config_page' => array (
  'default_inline_editing_column_form' => 'sfSympalPageForm',
  'default_rendering_module' => NULL,
  'default_rendering_action' => NULL,
  'default_content_template' => NULL,
  'default_theme' => NULL,
  'content_templates' => 
  array (
    'default_view' => 
    array (
      'template' => 'sympal_page/view',
    ),
    'register' => 
    array (
      'template' => 'sympal_register/page_template',
    ),
  ),
  'content_slots' => 
  array (
    'title' => 
    array (
      'type' => 'Text',
    ),
    'body' => 
    array (
      'type' => 'Markdown',
    ),
  ),
),
  'app_sympal_config_content-list' => array (
  'default_rendering_module' => NULL,
  'default_rendering_action' => NULL,
  'content_templates' => 
  array (
    'default_view' => 
    array (
      'template' => 'sympal_content_list/view',
    ),
  ),
),
  'app_sympal_config_auto_seo' => array (
  'title' => true,
  'title_format' => '%site_title% %separator% %ancestors%',
),
  'app_sympal_config_asset_paths' => NULL,
  'app_sympal_config_jquery_reloaded' => array (
  'path' => NULL,
  'plugin_paths' => NULL,
),
  'app_sympal_config_enable_markdown_editor' => true,
  'app_sympal_config_elastic_textareas' => true,
  'app_sympal_config_orm_cache' => array (
  'enabled' => true,
  'result' => false,
  'lifetime' => 86400,
  'queries' => 
  array (
    'sympal_get_content_types' => 
    array (
      'enabled' => true,
      'lifetime' => 86400,
    ),
    'sympal_get_user' => 
    array (
      'enabled' => true,
      'lifetime' => 86400,
    ),
    'sympal_context_get_site' => 
    array (
      'enabled' => true,
      'lifetime' => 86400,
    ),
    'sympal_get_content' => 
    array (
      'enabled' => true,
      'lifetime' => 86400,
    ),
  ),
),
  'app_sympal_config_page_cache' => array (
  'enabled' => false,
  'super' => false,
  'with_layout' => false,
  'lifetime' => 3600,
),
  'app_sympal_config_menu_cache' => array (
  'enabled' => true,
),
  'app_sympal_config_content_slot_types' => array (
  'Text' => 
  array (
    'label' => 'Single Line of Text',
    'transformers' => 
    array (
      0 => 'replacer',
    ),
  ),
  'RawHtml' => 
  array (
    'label' => 'Raw HTML',
    'transformers' => 
    array (
      0 => 'replacer',
    ),
  ),
  'Markdown' => 
  array (
    'label' => 'Markdown Editor',
    'transformers' => 
    array (
      0 => 'replacer',
      1 => 'markdown',
    ),
  ),
  'TinyMCE' => 
  array (
    'label' => 'TinyMCE Rich Text Editor',
    'widget_options' => 
    array (
      'config' => 'handle_event_callback : "sympalHandleTinyMCEEvent"',
    ),
    'transformers' => 
    array (
      0 => 'replacer',
    ),
  ),
  'Column' => 
  array (
    'label' => 'Column Slot Type',
    'widget_class' => false,
    'validator_class' => false,
  ),
),
  'app_sympal_config_slot_transformers' => array (
  'replacer' => 
  array (
    0 => 'sfSympalContentSlotReplacer',
    1 => 'transformSlotContent',
  ),
  'markdown' => 
  array (
    0 => 'sfSympalMarkdownRenderer',
    1 => 'convertToHtml',
  ),
),
  'app_sympal_config_check_for_upgrades_on_dashboard' => false,
  'app_sympal_config_enable_all_modules' => true,
  'app_sympal_config_disabled_modules' => array (
),
  'app_sympal_config_enabled_modules' => array (
),
  'app_sympal_config_get_cache_driver_callback' => array (
  0 => 'sfSympalCache',
  1 => 'getCacheDriver',
),
  'app_sympal_config_menu_manager_class' => 'sfSympalMenuSiteManager',
  'app_sympal_config_menu_class' => 'sfSympalMenuSite',
  'app_sympal_config_breadcrumbs_class' => 'sfSympalMenuBreadcrumbs',
  'app_sympal_config_admin_module_web_dir' => '/sfSympalAdminPlugin',
  'app_sympal_config_plugin_api' => array (
  'username' => NULL,
  'password' => NULL,
),
  'app_sympal_config_content_formats' => array (
  0 => 'html',
  1 => 'atom',
  2 => 'feed',
  3 => 'atom1',
  4 => 'rss',
  5 => 'rss10',
  6 => 'rss091',
  7 => 'rss201',
  8 => 'xml',
  9 => 'yml',
  10 => 'json',
),
  'app_sympal_config_breadcrumbs_separator' => ' / ',
  'app_sympal_config_i18n' => false,
  'app_sympal_config_internationalized_models' => array (
  'sfSympalContentList' => 
  array (
    0 => 'title',
  ),
  'sfSympalPage' => 
  array (
    0 => 'title',
  ),
),
  'app_sympal_config_sluggable_models' => array (
  'sfSympalAsset' => 
  array (
    'fields' => 
    array (
      0 => 'path',
      1 => 'name',
    ),
    'indexName' => 'asset_sluggable',
    'builder' => 
    array (
      0 => 'sfSympalAsset',
      1 => 'slugBuilder',
    ),
  ),
),
  'app_sympal_config_default_from_email_address' => 'noreply@sympalphp.org',
  'app_sympal_config_config_form_class' => 'sfSympalConfigForm',
  'app_sympal_config_recaptcha_public_key' => '6Ld2DgQAAAAAAApXLteupHPcbSxbSHkhNTuYLChX',
  'app_sympal_config_recaptcha_private_key' => '6Ld2DgQAAAAAANIbaXJsFEBOyg56CL_ljy3APlPb',
  'app_sympal_config_gravatar_default_image' => '/sfSympalPlugin/images/symfony_button.gif',
  'app_sympal_config_language_codes' => array (
),
  'app_sympal_config_default_admin_generator_theme' => 'sympal_admin',
  'app_sympal_config_admin_generator_class' => 'sfSympalDoctrineGenerator',
  'app_sympal_config_rows_per_page' => 10,
  'app_sympal_config_plugin_sources' => array (
  0 => 'http://svn.symfony-project.com/plugins',
),
  'app_sympal_config_markdown_styled_boxes' => array (
  0 => 'quote',
  1 => 'tip',
  2 => 'caution',
  3 => 'note',
),
));
